### PR TITLE
Add support for issues

### LINKED ISSUE #133: Add support for Issues

### PR DESCRIPTION
**Pull request by craftamap**
Hey there! 

I got a request for craftamap/bb#9 which needs access to the bitbucket issues.

I therefore started implementing them. :^) Note that this is still a draft. 

Closes #133

### CODE REVIEW

**Comment by ktrysmt** [comment]
Oh, thanks. @craftamap

**Comment by craftamap** [comment]
@ktrysmt Looks like I'm done here :) Ready for review!

As you can see, all issue endpoints except the attachment endpoint is implemented now. :)

**Comment by ktrysmt** [comment]
Looks good, I will.
And, would you please rebase it? @craftamap

**Comment by craftamap** [comment]
@ktrysmt I rebased now :)

**Review by ktrysmt — APPROVED** [review]
LGTM! Thanks a lot.

**Pull request merged**
