### PR TITLE
Crude implementation of pagination for repositories

### PR DESCRIPTION
**Pull request by mainiak**
Tested with [client.Repositories.ListForAccount(opts)](https://godoc.org/github.com/ktrysmt/go-bitbucket#Repositories.ListForAccount)

Code should be extended to support other API methods which support pagination

### CODE REVIEW

**Comment by ktrysmt** [comment]
LGTM.
Thank you for your implementations.

**Comment by ilius** [comment]
The pagination is not working. It's not even using the "next" URL (in the response json), and only sends one request, without any `page`/`offset` argument or input parameter.

**Comment by ktrysmt** [comment]
Oops I'll make some tests for it.

**Comment by ilius** [comment]
I implemented it in #26

**Pull request merged**
