### PR TITLE
feat: add support for webhook secrets

### PR DESCRIPTION
**Pull request by zachsmith1**
Adding support for secrets within webhooks. 

API ref: https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-hooks-post

### CODE REVIEW

**Comment by zachsmith1** [comment]
@peter-svensson mind taking a look?

**Comment by peter-svensson** [comment]
> @peter-svensson mind taking a look?

Looks good, however I'm not the real maintainer 😊 @ktrysmt will probably have to approve this.

**Comment by zachsmith1** [comment]
any thoughts @ktrysmt

**Review by ktrysmt — APPROVED** [review]
LGTM! Thank you for your contribution.

**Pull request merged**
