### PR TITLE
Add tests for branch permission deletion

### PR DESCRIPTION
**Pull request by oogali**
This PR allows one to eventually run the test suite repeatedly without manually intervening in the Bitbucket UI to clean up branch permission test resources.

### CODE REVIEW

**Review by ktrysmt — APPROVED** [review]
Thank you for your help!

**Comment by ktrysmt** [comment]
Please fix the conflicts. @oogali

**Comment by oogali** [comment]
Conflicts resolved.

**Comment by ktrysmt** [comment]
LGTM.

**Pull request merged**
