### PR TITLE
Add missing fields to repository

### PR DESCRIPTION
**Pull request by josemiguelmelo**

### CODE REVIEW

**Comment by craftamap** [comment]
Hey José,
I'm not the maintainer of this repository, but since I'm using this project quite frequently and even thought about creating this exact pull request, I'm very thankful you created it!

**Comment by josemiguelmelo** [comment]
Hey @craftamap,
Glad to know I'm also helping other people with this pull request :D

**Comment by souladm** [comment]
Hi, @ktrysmt 
Could you please rewiew this pr asap? By coincidence, I really need one of the fields that were added in this pr :)

**Comment by ktrysmt** [comment]
Thank you mention, I understood it. I overlooked catching up on adding and updating fields for each api.

**Comment by ktrysmt** [comment]
https://github.com/ktrysmt/go-bitbucket/releases/tag/v0.8.0

**Pull request merged**
