### PR TITLE
Add repository list tags method

### PR DESCRIPTION
**Pull request by csandanov**
I've noticed there're many changes in master that aren't in 0.4.1. Do you plan to release a new tag or should we using the master branch?

### CODE REVIEW

**Comment by ktrysmt** [comment]
Basically there is no room for maintenance for each minor version. I understand your desire to be provided a tag. I will provide tags from this time. @csandanov

**Comment by csandanov** [comment]
I'm currently using the fork with the list tags method I've added, on master branch. Works fine for me but I use just a few methods, a couple of them are new, I think, – list files and get file contents.

**Comment by ktrysmt** [comment]
Thank you for your reporting. I referenced it and I will merge it. LGTM.

**Comment by ktrysmt** [comment]
https://github.com/ktrysmt/go-bitbucket/releases/tag/v5.1.0
I released the new tag, too. @csandanov

**Comment by csandanov** [comment]
Hm... I'm not sure why you name the new version v5.x.x after there was only v0.4.1
Now go modules gives the following error:
```
version "v5.1.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v5
```

And it does so because of https://github.com/golang/go/wiki/Modules#semantic-import-versioning:

> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files 

So I guess if you want to stick to this v5, you should update your `go.mod` file and add `/v5` at the end of the first line. This way we'll be able to import it as `github.com/ktrysmt/go-bitbucket/v5`

**Comment by ktrysmt** [comment]
Oh sorry, I missed that rules of go.mods' versioning.
I will fix it to be suitable. 
Thank you for explain to me! @csandanov

**Comment by ktrysmt** [comment]
I re-released some tags about here.
I will so use v0.*.* for the time being that this project is still experimental and uncompletable.

**Comment by csandanov** [comment]
Thank you! it's all good now.

**Pull request merged**
